Fixed posix compliance and a few errors with variable handling

diff --git a/src/wsh b/src/wsh
--- a/src/wsh
+++ b/src/wsh
@@ -1,34 +1,34 @@
 #!/usr/bin/env sh
 
 # LIBRARY IMPORTS
-. /var/lib/warden/utilities/auth
-. /var/lib/warden/utilities/log
-. /var/lib/warden/utilities/array
+. /var/lib/warden/utilities/auth  # used for password authentication
+. /var/lib/warden/utilities/Log   # used for Logging
+. /var/lib/warden/utilities/array # used to manage command array (posix compliant)
 
 # CONFIG IMPORT
 . /etc/warden/warden.conf
 
-##################################
-##################################
 
 # LOCAL SESSION LOCK VARIABLE
 SESSION_LOCK=false
 
+
 # CHECK IF THE SESSION IS SSHD RELATED
 # AND SET VARIABLES APPROPIATELY
-if [ -z $SSH_CONNECTION ];then
+if [ -z "$SSH_CONNECTION" ];
+then
     SESSION_TYPE="SYS"
 else
     SESSION_TYPE="REM"
-	CLIENT_IP=$SSH_CONNECTION
+	CLIENT_IP=$(printf "%s" "$SSH_CONNECTION" | awk '{print $1}')
 fi
 
-CLIENT_TTY=$(ps hotty $$)
+CLIENT_TTY=$(ps hotty $$)  # grabs the device name for the users terminal instance
 
 
 # check if the entered argument is in the PERMITTED_COMMANDS array
 # as an element. Imported from config
-commandCheck () {
+CommandCheck () {
 	
 	OLD_IFS=$IFS
 	IFS=:
@@ -47,6 +47,9 @@ commandCheck () {
 
 }
 
+
+# The breakout command to escape the 
+# restricted shell
 Breakout () {
 
     if ! $SESSION_LOCK; 
@@ -55,51 +58,48 @@ Breakout () {
         then
             if [ "$SESSION_TYPE" = "REM" ];
             then
-                log "[BRKA][$SESSION_TYPE][$(date -u +"%Y%m%d-%H:%M:%S")] Breakout session created for $USER from $CLIENT_IP on $CLIENT_TTY"
+                Log "[BRKA][$SESSION_TYPE][$(date -u +"%Y%m%d-%H:%M:%S")] Breakout session created for $USER from $CLIENT_IP on $CLIENT_TTY"
             else
-                log "[BRKA][$SESSION_TYPE][$(date -u +"%Y%m%d-%H:%M:%S")] Breakout session created for $USER on $CLIENT_TTY"
+                Log "[BRKA][$SESSION_TYPE][$(date -u +"%Y%m%d-%H:%M:%S")] Breakout session created for $USER on $CLIENT_TTY"
             fi
-            # LOG ON SUCCESSFUL BREAKOUT
+            # Log ON SUCCESSFUL BREAKOUT
             /bin/bash
         else
             if [ "$SESSION_TYPE" = "REM" ];
             then
-                log "[LOCK][$SESSION_TYPE][$(date -u +"%Y%m%d-%H:%M:%S")] Account locked for $USER from $CLIENT_IP on $CLIENT_TTY"
+                Log "[LOCK][$SESSION_TYPE][$(date -u +"%Y%m%d-%H:%M:%S")] Account locked for $USER from $CLIENT_IP on $CLIENT_TTY"
             else
-                log "[LOCK][$SESSION_TYPE][$(date -u +"%Y%m%d-%H:%M:%S")] Account locked for $USER on $CLIENT_TTY"
+                Log "[LOCK][$SESSION_TYPE][$(date -u +"%Y%m%d-%H:%M:%S")] Account locked for $USER on $CLIENT_TTY"
             fi
-            # LOG ON SESSION LOCK
+            # Log ON SESSION LOCK
 
             SESSION_LOCK=true
         fi
     else 
-        # LOG ON SESSION DENIED
-        echo "Access Denied..."
+        # Log ON SESSION DENIED
+        printf "%s\n" "Access Denied..."
     fi
 
 }
 
-# Main executer
-# Checks if number of arguments is 0 
 
-# echo -e "[ CONNECTION ESTABLISHED ] ($(date +'%D %H:%M:%S')) $SSH_CLIENT_IP $USER" >> ~/blueshell_logs/log
-# the initial indicator of shell instance
-# notify-send -u critical "WARDEN STATUS: WARDEN-SHELL SESSION CREATED" "User <b>$USER</b> was logged in from <b>$SSH_CLIENT_IP</b> with terminal instance <b>$SSH_CLIENT_TTY</b> ($(date +'%D %H:%M:%S'))" 2> /dev/null
+# The shell environment that is spawned on exec (NON POSIX LOOP)
+Shell () {
 
-# The actual shell environment that the user is dropped into
-shell () {
-
+    # Log session type
     if [ "$SESSION_TYPE" = "REM" ];
     then
-        log "[SESO][$SESSION_TYPE][$(date -u +"%Y%m%d-%H:%M:%S")] Session created for $USER from $CLIENT_IP on $CLIENT_TTY"
+        Log "[SESO][$SESSION_TYPE][$(date -u +"%Y%m%d-%H:%M:%S")] Session created for $USER from $CLIENT_IP on $CLIENT_TTY"
     else
-        log "[SESO][$SESSION_TYPE][$(date -u +"%Y%m%d-%H:%M:%S")] Session created for $USER on $CLIENT_TTY"
+        Log "[SESO][$SESSION_TYPE][$(date -u +"%Y%m%d-%H:%M:%S")] Session created for $USER on $CLIENT_TTY"
     fi
+
     # Prevent user from exiting through 
     # keyboard calls
     trap '' INT TERM TSTP
     set -f
 
+    # if locks permit
     if ! checkLock $USER;
     then
 
@@ -119,7 +119,7 @@ shell () {
             ;;
 
             *[^a-zA-Z0-9_.\ /-]*)
-                log "[CMDB][$SESSION_TYPE][$(date -u +"%Y%m%d-%H:%M:%S")] $input"
+                Log "[CMDB][$SESSION_TYPE][$(date -u +"%Y%m%d-%H:%M:%S")] $input"
                 # Commands that contain any weird characters will be thrown this error
                 printf '%s\n' "ERROR: Command may contain restricted characters..."
             ;;
@@ -133,27 +133,27 @@ shell () {
 
                 if [ "$command" = "exit" ]; # If command is exit
                 then
-                    # LOG ON EXIT
-                    log "[SESE][$SESSION_TYPE][$(date -u +"%Y%m%d-%H:%M:%S")] Session closed for $USER on $CLIENT_TTY"
+                    # Log ON EXIT
+                    Log "[SESE][$SESSION_TYPE][$(date -u +"%Y%m%d-%H:%M:%S")] Session closed for $USER on $CLIENT_TTY"
 
                     exit 0
                 elif [ "$command" = "$BREAKOUT_COMMAND" ];
                 then
-                    # LOG ON BREAKOUT REQUEST
-                    log "[BRKR][$SESSION_TYPE][$(date -u +"%Y%m%d-%H:%M:%S") Session breakout requested for $USER on $CLIENT_TTY"
+                    # Log ON BREAKOUT REQUEST
+                    Log "[BRKR][$SESSION_TYPE][$(date -u +"%Y%m%d-%H:%M:%S")] Session breakout requested for $USER on $CLIENT_TTY"
 
                     Breakout
-                elif commandCheck "$command"; # If command check passes
+                elif CommandCheck "$command"; # If command check passes
                 then
-                    # LOG ON COMMAND EXEC
-                    log "[CMDA][$SESSION_TYPE][$(date -u +"%Y%m%d-%H:%M:%S")] $command $@"
+                    # Log ON COMMAND EXEC
+                    Log "[CMDA][$SESSION_TYPE][$(date -u +"%Y%m%d-%H:%M:%S")] $command $@"
                     
 
                     "$command" "$@" 2> /dev/null
 
                 else
-                    # LOG ON UNAVAILABLE COMMANDS
-                    log "[CMDB][$SESSION_TYPE][$(date -u +"%Y%m%d-%H:%M:%S")] $command $@"
+                    # Log ON UNAVAILABLE COMMANDS
+                    Log "[CMDB][$SESSION_TYPE][$(date -u +"%Y%m%d-%H:%M:%S")] $command $@"
 
                     printf '%s\n' "$command command not available..."
                 fi
@@ -162,11 +162,104 @@ shell () {
             esac
         done
     else
-        log "[SESE][$SESSION_TYPE][$(date -u +"%Y%m%d-%H:%M:%S")] Session denied for $USER due to lock"
+        Log "[SESE][$SESSION_TYPE][$(date -u +"%Y%m%d-%H:%M:%S")] Session denied for $USER due to lock"
     fi
     
     exit 0
 
 }
 
-shell
+
+# The shell environment that is spawned on exec (POSIX COMPLIANT LOOP)
+PosixShell () {
+
+    # Log session type
+    if [ "$SESSION_TYPE" = "REM" ];
+    then
+        Log "[SESO][$SESSION_TYPE][$(date -u +"%Y%m%d-%H:%M:%S")] Session created for $USER from $CLIENT_IP on $CLIENT_TTY"
+    else
+        Log "[SESO][$SESSION_TYPE][$(date -u +"%Y%m%d-%H:%M:%S")] Session created for $USER on $CLIENT_TTY"
+    fi
+
+    # Prevent user from exiting through 
+    # keyboard calls
+    trap '' INT TERM TSTP
+    set -f
+
+    # if locks permit
+    if ! checkLock $USER;
+    then
+
+        # -e removal of -e and -p are for posix compliance
+        cd $HOME
+        while printf "%s" "$(pwd) $ " && read -r  input
+        do
+
+            # Preliminary case check for shell
+            # meta/escape characters.
+            # Should only filter for dashes and alphanumerics
+            case "$input" in
+
+            "")
+            ;;
+
+            *[^a-zA-Z0-9_.\ /-]*)
+                Log "[CMDB][$SESSION_TYPE][$(date -u +"%Y%m%d-%H:%M:%S")] $input"
+                # Commands that contain any weird characters will be thrown this error
+                printf '%s\n' "ERROR: Command may contain restricted characters..."
+            ;;
+
+            *)
+                # Input sanitation for any strays
+                input=$(printf '%s' "$input" | tr -d ';&|><$`\\'\''"')
+                set -- $input # Breaks apart the command into constituent parts
+                command="$1" # The first command run will have a prelim check
+                shift # separates arguments and commands
+
+                if [ "$command" = "exit" ]; # If command is exit
+                then
+                    # Log ON EXIT
+                    Log "[SESE][$SESSION_TYPE][$(date -u +"%Y%m%d-%H:%M:%S")] Session closed for $USER on $CLIENT_TTY"
+
+                    exit 0
+                elif [ "$command" = "$BREAKOUT_COMMAND" ];
+                then
+                    # Log ON BREAKOUT REQUEST
+                    Log "[BRKR][$SESSION_TYPE][$(date -u +"%Y%m%d-%H:%M:%S")] Session breakout requested for $USER on $CLIENT_TTY"
+
+                    Breakout
+                elif CommandCheck "$command"; # If command check passes
+                then
+                    # Log ON COMMAND EXEC
+                    Log "[CMDA][$SESSION_TYPE][$(date -u +"%Y%m%d-%H:%M:%S")] $command $@"
+                    
+
+                    "$command" "$@" 2> /dev/null
+
+                else
+                    # Log ON UNAVAILABLE COMMANDS
+                    Log "[CMDB][$SESSION_TYPE][$(date -u +"%Y%m%d-%H:%M:%S")] $command $@"
+
+                    printf '%s\n' "$command command not available..."
+                fi
+            ;;
+        
+            esac
+        done
+    else
+        Log "[SESE][$SESSION_TYPE][$(date -u +"%Y%m%d-%H:%M:%S")] Session denied for $USER due to lock"
+    fi
+    
+    exit 0
+
+}
+
+
+# Check if the shell engine is bash compatible and
+# run the compliant shell function
+if [ -n "$BASH_VERSION" ];
+then 
+    Shell
+else
+    PosixShell
+fi
